
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: DBSource
//     Provider:               Npgsql
//     Connection String:      Server=localhost;Database=northwind_mini;User Id=postgres;password=**zapped**;
//     Schema:                 
//     Include Views:          False

//     Factory Name:          'NpgsqlFactory'
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;

namespace NorthwindMini.Model
{
    public partial class category 
    {
        [Required]
		[Key]
        public long category_id { get; set;}
        [Required]
        public string category_name { get; set;}
        public string description { get; set;}
        public byte[] picture { get; set;}
    }
    public partial class product 
    {
        [Required]
		[Key]
        public long product_id { get; set;}
        [Required]
        public string product_name { get; set;}
        public short? supplier_id { get; set;}
        public short? category_id { get; set;}
        public string quantity_per_unit { get; set;}
        public float? unit_price { get; set;}
        public short? units_in_stock { get; set;}
        public short? units_on_order { get; set;}
        public short? reorder_level { get; set;}
        [Required]
        public int discontinued { get; set;}
    }
    public partial class customer 
    {
        [Required]
		[Key]
        public string customer_id { get; set;}
        [Required]
        public string company_name { get; set;}
        public string contact_name { get; set;}
        public string contact_title { get; set;}
        public string address { get; set;}
        public string city { get; set;}
        public string region { get; set;}
        public string postal_code { get; set;}
        public string country { get; set;}
        public string phone { get; set;}
        public string fax { get; set;}
    }
}
#pragma warning restore 1591


