
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: DBSource
//     Provider:               Npgsql Local
//     Connection String:      Server=localhost;Database=northwind_mini;User Id=postgres;password=**zapped**;
//     Schema:                 
//     Include Views:          False


// -----------------------------------------------------------------------------------------
// Failed to load provider 'Npgsql Local' - Unable to find the requested .Net Framework Data Provider.  It may not be installed.
// -----------------------------------------------------------------------------------------



